### ISSUE TITLE
Date sorting bug

### ISSUE THREAD

**Issue by ViktorKahu** [Goodwy/Gallery#1]
Hi, thanks for a great suite of apps.

I would like to report a minor bug in your gallery app.

When photos in the album are sorted by month (currently its December), November 2023 is shown at the top, followed by October and every other month, with December right at the bottom.

Swtching the order between ascending and descending keeps November at the top, followed by february, etc, with December at the very bottom again.

Thanks for your time and attention to this matter.

**Comment by Goodwy** [comment]
Hello, 
There is no sorting by month in the application, there is grouping by month. Most likely you have grouping by month set, and sorting is not by date, but by some other parameter.

**Comment by ViktorKahu** [comment]
Apologies for wrong terminology.

I have grouping by month, and sorting by creation date.

**Comment by Goodwy** [comment]
Can you attach screenshots of grouping and sorting settings and the result.

**Comment by ViktorKahu** [comment]
![Screenshot_20231228-032207](https://github.com/Goodwy/Gallery/assets/125934998/a87e0ef0-6a0e-4113-a650-0c977901746d)
![Screenshot_20231228-032215_1](https://github.com/Goodwy/Gallery/assets/125934998/9effe34b-382a-40ec-8954-39e71db106ea)

The month at the top translates to November, bottom December.

The other settings translate to creation date and descending.

The goal is to have the current month at the top and the following lower. Currently not the case. Even for different years, for some reason November is always first and december is always last with every other month in between.

If i have descending selected, i would get: November 2023, October2023, etc... with December 2023 last.

If ascending: November 2023, January 2023, February 2023, etc... with December once again, last.

**Comment by Goodwy** [comment]
Send me a screenshot of the grouping settings as well.

**Comment by ViktorKahu** [comment]
I thought the items at the bottom (selection of the groupeng) were the grouping settings. Now that you mentioned that, I found them and there actually is no fault. My bad.

Thanks for your help, apologies for wasting your time.
