### ISSUE TITLE
Battery icon and gesture bar does not hide with the rest of the UI

### ISSUE THREAD

**Issue by GaucovyAero** [Goodwy/Gallery#10]
Device: Xiaomi Poco F3 8/256
OS: crDroid 10.7 (Android 14), issue also present on LineageOS 21 (Android 14)

Issue is also present in the Fossify Gallery and Simple Gallery.

https://github.com/user-attachments/assets/41cff4d7-6f2c-4f13-8717-5508ba33cea6

**Comment by Goodwy** [comment]
It's a feature of newer versions of Android.
