### ISSUE TITLE
Goes back to the first image when changing orientation

### ISSUE THREAD

**Issue by GaucovyAero** [Goodwy/Gallery#12]
Device: Xiaomi Poco F3 8/256
OS: crDroid 10.7 (Android 14) - August 16 build

https://github.com/user-attachments/assets/2addf86c-e311-4ec0-a9e6-960c3690488e

**Comment by Goodwy** [comment]
Fixed on version 5.5.0+

**Comment by Goodwy** [comment]
In version 5.5.0+, added the ability to disable the top bar from changing when scrolling.
