### ISSUE TITLE
Is Network Permission necessary ?

### ISSUE THREAD

**Issue by sonalder-darlene** [Goodwy/Gallery#14]
Hi, your forks of SimpleMobileTools apps looks really great from both a UI and A UX standpoint but I was wondering why does they require the network permission if you don't collect data. At first I was thinking for Right Messages it was for sending and recieving MMS but Right Contacts, Right Gallery and Right Dialer.

I think it shouldn't requiere such permission as the seems for many of your apps unnecessary

**Comment by Goodwy** [comment]
Hi, these permissions are only required to make in-app purchases.  For everything else, we keep as much privacy as possible as a Simple app.
