### ISSUE TITLE
Videos unstable and crashing.

### ISSUE THREAD

**Issue by ghost** [Goodwy/Gallery#3]
When a lot of videos are watched in a row, sometimes it exits to the album view mid video, sometimes crashes the app, sometimes black screen.

I did get a crash log but unfortunately have since lost it. It said something about "unable to allocate "x" bits of memory with "y" bits available (y was more than x).

**Comment by Khaledsame** [comment]
That's what happens with me, But it just goes a bit further, At crashes all the time, every video is being watched the app automatically crashes and exit the app.

**Comment by Goodwy** [comment]
What kind of device do you have?

**Comment by ViktorKahu** [comment]
Pixel 7 pro 
GrapgeneOS
A14

**Comment by Khaledsame** [comment]
And i'm using
Xiaomi Mi A1
SparkOS (Custom ROM)
A13

**Comment by Khaledsame** [comment]
Any news??

**Comment by Goodwy** [comment]
So far, I have not been able to reproduce such a problem.

**Comment by ViktorKahu** [comment]
Here is an avenue to explore:

https://github.com/deckerst/aves/issues/722

Could something like this apply to your app?

**Comment by Goodwy** [comment]
The media-kit was the problem there, and we don't use it.

**Comment by Goodwy** [comment]
Fixed on version 5.5.0+
